Structurize files
Make structure more clean, move alembic and pytests from `./app` project
directory

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -1,20 +1,26 @@
-FROM docker.io/library/python:3.13.7-alpine3.21
+FROM docker.io/library/python:3.13.7-alpine3.22
 
 # Install uv
 # Ref: https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
 COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
 
+RUN apk add --no-cache curl && \
+  curl -I https://pypi.org/ || echo "Network test failed"
 WORKDIR /backend
+ENV PYTHONPATH=./
+
 # Compile bytecode
 # Ref: https://docs.astral.sh/uv/guides/integration/docker/#compiling-bytecode
 ENV UV_COMPILE_BYTECODE=1
 
-COPY ./uv.lock ./pyproject.toml ./pyproject.toml ./
-
+COPY ./uv.lock ./pyproject.toml ./
 RUN uv sync --frozen
 
-COPY ./app ./app
+COPY ./app/ ./app/
+COPY ./tests/ ./tests/
+
 COPY ./alembic.ini ./
+COPY ./alembic/ ./alembic/
 
 CMD ["uv", "run", "fastapi", "run", "--workers", "4", "./app/main.py"]
 
